volumes:
  moneyminder:
    external: true
  pg-admin:
    external: true
services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://moneyminder:moneyminder@db/moneyminder
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      SIGNING_KEY: 94adf71a8a30eecb1f5848f6808795dfe6f308be3582a2a37bc45b8c2db37a6d
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}

  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - moneyminder:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: moneyminder
      POSTGRES_USER: moneyminder
      POSTGRES_DB: moneyminder
    ports:
      - "15432:5432"

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: me@me.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
